/*
 * This file is generated by jOOQ.
 */
package er.codes.secretsaltyminimal.jooq


import er.codes.secretsaltyminimal.jooq.tables.Assignments
import er.codes.secretsaltyminimal.jooq.tables.Exemptions
import er.codes.secretsaltyminimal.jooq.tables.Users

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Public : SchemaImpl(DSL.name("public"), DefaultCatalog.DEFAULT_CATALOG, DSL.comment("")) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.assignments</code>.
     */
    val ASSIGNMENTS: Assignments get() = Assignments.ASSIGNMENTS

    /**
     * The table <code>public.exemptions</code>.
     */
    val EXEMPTIONS: Exemptions get() = Exemptions.EXEMPTIONS

    /**
     * The table <code>public.users</code>.
     */
    val USERS: Users get() = Users.USERS

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Assignments.ASSIGNMENTS,
        Exemptions.EXEMPTIONS,
        Users.USERS
    )
}
