/*
 * This file is generated by jOOQ.
 */
package er.codes.secretsaltyminimal.jooq.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class Assignments(
    var giverId: String? = null,
    var receiverId: String? = null,
    var createdAt: LocalDateTime? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Assignments = other as Assignments
        if (this.giverId == null) {
            if (o.giverId != null)
                return false
        }
        else if (this.giverId != o.giverId)
            return false
        if (this.receiverId == null) {
            if (o.receiverId != null)
                return false
        }
        else if (this.receiverId != o.receiverId)
            return false
        if (this.createdAt == null) {
            if (o.createdAt != null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.giverId == null) 0 else this.giverId.hashCode())
        result = prime * result + (if (this.receiverId == null) 0 else this.receiverId.hashCode())
        result = prime * result + (if (this.createdAt == null) 0 else this.createdAt.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Assignments (")

        sb.append(giverId)
        sb.append(", ").append(receiverId)
        sb.append(", ").append(createdAt)

        sb.append(")")
        return sb.toString()
    }
}
