/*
 * This file is generated by jOOQ.
 */
package er.codes.secretsaltyminimal.jooq.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class Exemptions(
    var userId: String? = null,
    var excludedUserId: String? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Exemptions = other as Exemptions
        if (this.userId == null) {
            if (o.userId != null)
                return false
        }
        else if (this.userId != o.userId)
            return false
        if (this.excludedUserId == null) {
            if (o.excludedUserId != null)
                return false
        }
        else if (this.excludedUserId != o.excludedUserId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.userId == null) 0 else this.userId.hashCode())
        result = prime * result + (if (this.excludedUserId == null) 0 else this.excludedUserId.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Exemptions (")

        sb.append(userId)
        sb.append(", ").append(excludedUserId)

        sb.append(")")
        return sb.toString()
    }
}
