/*
 * This file is generated by jOOQ.
 */
package er.codes.secretsaltyminimal.jooq.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class Users(
    var userId: String? = null,
    var username: String? = null,
    var wishes: String? = null,
    var firstSeenAt: LocalDateTime? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Users = other as Users
        if (this.userId == null) {
            if (o.userId != null)
                return false
        }
        else if (this.userId != o.userId)
            return false
        if (this.username == null) {
            if (o.username != null)
                return false
        }
        else if (this.username != o.username)
            return false
        if (this.wishes == null) {
            if (o.wishes != null)
                return false
        }
        else if (this.wishes != o.wishes)
            return false
        if (this.firstSeenAt == null) {
            if (o.firstSeenAt != null)
                return false
        }
        else if (this.firstSeenAt != o.firstSeenAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.userId == null) 0 else this.userId.hashCode())
        result = prime * result + (if (this.username == null) 0 else this.username.hashCode())
        result = prime * result + (if (this.wishes == null) 0 else this.wishes.hashCode())
        result = prime * result + (if (this.firstSeenAt == null) 0 else this.firstSeenAt.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Users (")

        sb.append(userId)
        sb.append(", ").append(username)
        sb.append(", ").append(wishes)
        sb.append(", ").append(firstSeenAt)

        sb.append(")")
        return sb.toString()
    }
}
