@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package er.codes.secretsaltyminimal.jooq.tables.references


import er.codes.secretsaltyminimal.jooq.tables.Assignments
import er.codes.secretsaltyminimal.jooq.tables.Exemptions
import er.codes.secretsaltyminimal.jooq.tables.Users



/**
 * The table <code>public.assignments</code>.
 */
val ASSIGNMENTS: Assignments = Assignments.ASSIGNMENTS

/**
 * The table <code>public.exemptions</code>.
 */
val EXEMPTIONS: Exemptions = Exemptions.EXEMPTIONS

/**
 * The table <code>public.users</code>.
 */
val USERS: Users = Users.USERS
