/*
 * This file is generated by jOOQ.
 */
package er.codes.secretsaltyminimal.jooq.tables.records


import er.codes.secretsaltyminimal.jooq.tables.Assignments

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class AssignmentsRecord() : UpdatableRecordImpl<AssignmentsRecord>(Assignments.ASSIGNMENTS) {

    open var giverId: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var receiverId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised AssignmentsRecord
     */
    constructor(giverId: String? = null, receiverId: String? = null, createdAt: LocalDateTime? = null): this() {
        this.giverId = giverId
        this.receiverId = receiverId
        this.createdAt = createdAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised AssignmentsRecord
     */
    constructor(value: er.codes.secretsaltyminimal.jooq.tables.pojos.Assignments?): this() {
        if (value != null) {
            this.giverId = value.giverId
            this.receiverId = value.receiverId
            this.createdAt = value.createdAt
            resetTouchedOnNotNull()
        }
    }
}
