/*
 * This file is generated by jOOQ.
 */
package er.codes.secretsaltyminimal.jooq.tables.records


import er.codes.secretsaltyminimal.jooq.tables.Exemptions

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ExemptionsRecord() : UpdatableRecordImpl<ExemptionsRecord>(Exemptions.EXEMPTIONS) {

    open var userId: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var excludedUserId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<String?, String?> = super.key() as Record2<String?, String?>

    /**
     * Create a detached, initialised ExemptionsRecord
     */
    constructor(userId: String? = null, excludedUserId: String? = null): this() {
        this.userId = userId
        this.excludedUserId = excludedUserId
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised ExemptionsRecord
     */
    constructor(value: er.codes.secretsaltyminimal.jooq.tables.pojos.Exemptions?): this() {
        if (value != null) {
            this.userId = value.userId
            this.excludedUserId = value.excludedUserId
            resetTouchedOnNotNull()
        }
    }
}
