/*
 * This file is generated by jOOQ.
 */
package er.codes.secretsaltyminimal.jooq.tables.records


import er.codes.secretsaltyminimal.jooq.tables.Users

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class UsersRecord() : UpdatableRecordImpl<UsersRecord>(Users.USERS) {

    open var userId: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var username: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var wishes: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var firstSeenAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised UsersRecord
     */
    constructor(userId: String? = null, username: String? = null, wishes: String? = null, firstSeenAt: LocalDateTime? = null): this() {
        this.userId = userId
        this.username = username
        this.wishes = wishes
        this.firstSeenAt = firstSeenAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    constructor(value: er.codes.secretsaltyminimal.jooq.tables.pojos.Users?): this() {
        if (value != null) {
            this.userId = value.userId
            this.username = value.username
            this.wishes = value.wishes
            this.firstSeenAt = value.firstSeenAt
            resetTouchedOnNotNull()
        }
    }
}
