/*
 * This file is generated by jOOQ.
 */
package er.codes.secretsaltyminimal.jooq.tables


import er.codes.secretsaltyminimal.jooq.Public
import er.codes.secretsaltyminimal.jooq.indexes.IDX_ASSIGNMENTS_RECEIVER
import er.codes.secretsaltyminimal.jooq.keys.ASSIGNMENTS_PKEY
import er.codes.secretsaltyminimal.jooq.keys.ASSIGNMENTS_RECEIVER_ID_KEY
import er.codes.secretsaltyminimal.jooq.keys.ASSIGNMENTS__ASSIGNMENTS_GIVER_ID_FKEY
import er.codes.secretsaltyminimal.jooq.keys.ASSIGNMENTS__ASSIGNMENTS_RECEIVER_ID_FKEY
import er.codes.secretsaltyminimal.jooq.tables.Users.UsersPath
import er.codes.secretsaltyminimal.jooq.tables.records.AssignmentsRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Check
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Assignments(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, AssignmentsRecord>?,
    parentPath: InverseForeignKey<out Record, AssignmentsRecord>?,
    aliased: Table<AssignmentsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<AssignmentsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.assignments</code>
         */
        val ASSIGNMENTS: Assignments = Assignments()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AssignmentsRecord> = AssignmentsRecord::class.java

    /**
     * The column <code>public.assignments.giver_id</code>.
     */
    val GIVER_ID: TableField<AssignmentsRecord, String?> = createField(DSL.name("giver_id"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>public.assignments.receiver_id</code>.
     */
    val RECEIVER_ID: TableField<AssignmentsRecord, String?> = createField(DSL.name("receiver_id"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>public.assignments.created_at</code>.
     */
    val CREATED_AT: TableField<AssignmentsRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<AssignmentsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<AssignmentsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<AssignmentsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.assignments</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.assignments</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.assignments</code> table reference
     */
    constructor(): this(DSL.name("assignments"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AssignmentsRecord>?, parentPath: InverseForeignKey<out Record, AssignmentsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, ASSIGNMENTS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class AssignmentsPath : Assignments, Path<AssignmentsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AssignmentsRecord>?, parentPath: InverseForeignKey<out Record, AssignmentsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<AssignmentsRecord>): super(alias, aliased)
        override fun `as`(alias: String): AssignmentsPath = AssignmentsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): AssignmentsPath = AssignmentsPath(alias, this)
        override fun `as`(alias: Table<*>): AssignmentsPath = AssignmentsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_ASSIGNMENTS_RECEIVER)
    override fun getPrimaryKey(): UniqueKey<AssignmentsRecord> = ASSIGNMENTS_PKEY
    override fun getUniqueKeys(): List<UniqueKey<AssignmentsRecord>> = listOf(ASSIGNMENTS_RECEIVER_ID_KEY)
    override fun getReferences(): List<ForeignKey<AssignmentsRecord, *>> = listOf(ASSIGNMENTS__ASSIGNMENTS_GIVER_ID_FKEY, ASSIGNMENTS__ASSIGNMENTS_RECEIVER_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>assignments_giver_id_fkey</code> key.
     */
    fun assignmentsGiverIdFkey(): UsersPath = assignmentsGiverIdFkey
    val assignmentsGiverIdFkey: UsersPath by lazy { UsersPath(this, ASSIGNMENTS__ASSIGNMENTS_GIVER_ID_FKEY, null) }

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>assignments_receiver_id_fkey</code> key.
     */
    fun assignmentsReceiverIdFkey(): UsersPath = assignmentsReceiverIdFkey
    val assignmentsReceiverIdFkey: UsersPath by lazy { UsersPath(this, ASSIGNMENTS__ASSIGNMENTS_RECEIVER_ID_FKEY, null) }
    override fun getChecks(): List<Check<AssignmentsRecord>> = listOf(
        Internal.createCheck(this, DSL.name("chk_assignment_no_self"), "(((giver_id)::text <> (receiver_id)::text))", true)
    )
    override fun `as`(alias: String): Assignments = Assignments(DSL.name(alias), this)
    override fun `as`(alias: Name): Assignments = Assignments(alias, this)
    override fun `as`(alias: Table<*>): Assignments = Assignments(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Assignments = Assignments(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Assignments = Assignments(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Assignments = Assignments(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Assignments = Assignments(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Assignments = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Assignments = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Assignments = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Assignments = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Assignments = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Assignments = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Assignments = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Assignments = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Assignments = where(DSL.notExists(select))
}
