/*
 * This file is generated by jOOQ.
 */
package er.codes.secretsaltyminimal.jooq.tables


import er.codes.secretsaltyminimal.jooq.Public
import er.codes.secretsaltyminimal.jooq.indexes.IDX_EXEMPTIONS_USER
import er.codes.secretsaltyminimal.jooq.keys.EXEMPTIONS_PKEY
import er.codes.secretsaltyminimal.jooq.keys.EXEMPTIONS__EXEMPTIONS_EXCLUDED_USER_ID_FKEY
import er.codes.secretsaltyminimal.jooq.keys.EXEMPTIONS__EXEMPTIONS_USER_ID_FKEY
import er.codes.secretsaltyminimal.jooq.tables.Users.UsersPath
import er.codes.secretsaltyminimal.jooq.tables.records.ExemptionsRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Check
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Exemptions(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ExemptionsRecord>?,
    parentPath: InverseForeignKey<out Record, ExemptionsRecord>?,
    aliased: Table<ExemptionsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ExemptionsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.exemptions</code>
         */
        val EXEMPTIONS: Exemptions = Exemptions()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ExemptionsRecord> = ExemptionsRecord::class.java

    /**
     * The column <code>public.exemptions.user_id</code>.
     */
    val USER_ID: TableField<ExemptionsRecord, String?> = createField(DSL.name("user_id"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>public.exemptions.excluded_user_id</code>.
     */
    val EXCLUDED_USER_ID: TableField<ExemptionsRecord, String?> = createField(DSL.name("excluded_user_id"), SQLDataType.VARCHAR.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<ExemptionsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ExemptionsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ExemptionsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.exemptions</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.exemptions</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.exemptions</code> table reference
     */
    constructor(): this(DSL.name("exemptions"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ExemptionsRecord>?, parentPath: InverseForeignKey<out Record, ExemptionsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, EXEMPTIONS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ExemptionsPath : Exemptions, Path<ExemptionsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ExemptionsRecord>?, parentPath: InverseForeignKey<out Record, ExemptionsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ExemptionsRecord>): super(alias, aliased)
        override fun `as`(alias: String): ExemptionsPath = ExemptionsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ExemptionsPath = ExemptionsPath(alias, this)
        override fun `as`(alias: Table<*>): ExemptionsPath = ExemptionsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_EXEMPTIONS_USER)
    override fun getPrimaryKey(): UniqueKey<ExemptionsRecord> = EXEMPTIONS_PKEY
    override fun getReferences(): List<ForeignKey<ExemptionsRecord, *>> = listOf(EXEMPTIONS__EXEMPTIONS_EXCLUDED_USER_ID_FKEY, EXEMPTIONS__EXEMPTIONS_USER_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>exemptions_excluded_user_id_fkey</code> key.
     */
    fun exemptionsExcludedUserIdFkey(): UsersPath = exemptionsExcludedUserIdFkey
    val exemptionsExcludedUserIdFkey: UsersPath by lazy { UsersPath(this, EXEMPTIONS__EXEMPTIONS_EXCLUDED_USER_ID_FKEY, null) }

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>exemptions_user_id_fkey</code> key.
     */
    fun exemptionsUserIdFkey(): UsersPath = exemptionsUserIdFkey
    val exemptionsUserIdFkey: UsersPath by lazy { UsersPath(this, EXEMPTIONS__EXEMPTIONS_USER_ID_FKEY, null) }
    override fun getChecks(): List<Check<ExemptionsRecord>> = listOf(
        Internal.createCheck(this, DSL.name("chk_exemption_no_self"), "(((user_id)::text <> (excluded_user_id)::text))", true)
    )
    override fun `as`(alias: String): Exemptions = Exemptions(DSL.name(alias), this)
    override fun `as`(alias: Name): Exemptions = Exemptions(alias, this)
    override fun `as`(alias: Table<*>): Exemptions = Exemptions(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Exemptions = Exemptions(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Exemptions = Exemptions(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Exemptions = Exemptions(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Exemptions = Exemptions(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Exemptions = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Exemptions = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Exemptions = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Exemptions = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Exemptions = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Exemptions = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Exemptions = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Exemptions = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Exemptions = where(DSL.notExists(select))
}
