/*
 * This file is generated by jOOQ.
 */
package er.codes.secretsaltyminimal.jooq.tables


import er.codes.secretsaltyminimal.jooq.Public
import er.codes.secretsaltyminimal.jooq.keys.ASSIGNMENTS__ASSIGNMENTS_GIVER_ID_FKEY
import er.codes.secretsaltyminimal.jooq.keys.ASSIGNMENTS__ASSIGNMENTS_RECEIVER_ID_FKEY
import er.codes.secretsaltyminimal.jooq.keys.EXEMPTIONS__EXEMPTIONS_EXCLUDED_USER_ID_FKEY
import er.codes.secretsaltyminimal.jooq.keys.EXEMPTIONS__EXEMPTIONS_USER_ID_FKEY
import er.codes.secretsaltyminimal.jooq.keys.USERS_PKEY
import er.codes.secretsaltyminimal.jooq.keys.USERS_USERNAME_KEY
import er.codes.secretsaltyminimal.jooq.tables.Assignments.AssignmentsPath
import er.codes.secretsaltyminimal.jooq.tables.Exemptions.ExemptionsPath
import er.codes.secretsaltyminimal.jooq.tables.records.UsersRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Users(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, UsersRecord>?,
    parentPath: InverseForeignKey<out Record, UsersRecord>?,
    aliased: Table<UsersRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<UsersRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.users</code>
         */
        val USERS: Users = Users()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UsersRecord> = UsersRecord::class.java

    /**
     * The column <code>public.users.user_id</code>.
     */
    val USER_ID: TableField<UsersRecord, String?> = createField(DSL.name("user_id"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>public.users.username</code>.
     */
    val USERNAME: TableField<UsersRecord, String?> = createField(DSL.name("username"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.users.wishes</code>.
     */
    val WISHES: TableField<UsersRecord, String?> = createField(DSL.name("wishes"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.users.first_seen_at</code>.
     */
    val FIRST_SEEN_AT: TableField<UsersRecord, LocalDateTime?> = createField(DSL.name("first_seen_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<UsersRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<UsersRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<UsersRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.users</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.users</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.users</code> table reference
     */
    constructor(): this(DSL.name("users"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UsersRecord>?, parentPath: InverseForeignKey<out Record, UsersRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, USERS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class UsersPath : Users, Path<UsersRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UsersRecord>?, parentPath: InverseForeignKey<out Record, UsersRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<UsersRecord>): super(alias, aliased)
        override fun `as`(alias: String): UsersPath = UsersPath(DSL.name(alias), this)
        override fun `as`(alias: Name): UsersPath = UsersPath(alias, this)
        override fun `as`(alias: Table<*>): UsersPath = UsersPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<UsersRecord> = USERS_PKEY
    override fun getUniqueKeys(): List<UniqueKey<UsersRecord>> = listOf(USERS_USERNAME_KEY)

    private lateinit var _assignmentsGiverIdFkey: AssignmentsPath

    /**
     * Get the implicit to-many join path to the <code>public.assignments</code>
     * table, via the <code>assignments_giver_id_fkey</code> key
     */
    fun assignmentsGiverIdFkey(): AssignmentsPath {
        if (!this::_assignmentsGiverIdFkey.isInitialized)
            _assignmentsGiverIdFkey = AssignmentsPath(this, null, ASSIGNMENTS__ASSIGNMENTS_GIVER_ID_FKEY.inverseKey)

        return _assignmentsGiverIdFkey;
    }

    val assignmentsGiverIdFkey: AssignmentsPath
        get(): AssignmentsPath = assignmentsGiverIdFkey()

    private lateinit var _assignmentsReceiverIdFkey: AssignmentsPath

    /**
     * Get the implicit to-many join path to the <code>public.assignments</code>
     * table, via the <code>assignments_receiver_id_fkey</code> key
     */
    fun assignmentsReceiverIdFkey(): AssignmentsPath {
        if (!this::_assignmentsReceiverIdFkey.isInitialized)
            _assignmentsReceiverIdFkey = AssignmentsPath(this, null, ASSIGNMENTS__ASSIGNMENTS_RECEIVER_ID_FKEY.inverseKey)

        return _assignmentsReceiverIdFkey;
    }

    val assignmentsReceiverIdFkey: AssignmentsPath
        get(): AssignmentsPath = assignmentsReceiverIdFkey()

    private lateinit var _exemptionsExcludedUserIdFkey: ExemptionsPath

    /**
     * Get the implicit to-many join path to the <code>public.exemptions</code>
     * table, via the <code>exemptions_excluded_user_id_fkey</code> key
     */
    fun exemptionsExcludedUserIdFkey(): ExemptionsPath {
        if (!this::_exemptionsExcludedUserIdFkey.isInitialized)
            _exemptionsExcludedUserIdFkey = ExemptionsPath(this, null, EXEMPTIONS__EXEMPTIONS_EXCLUDED_USER_ID_FKEY.inverseKey)

        return _exemptionsExcludedUserIdFkey;
    }

    val exemptionsExcludedUserIdFkey: ExemptionsPath
        get(): ExemptionsPath = exemptionsExcludedUserIdFkey()

    private lateinit var _exemptionsUserIdFkey: ExemptionsPath

    /**
     * Get the implicit to-many join path to the <code>public.exemptions</code>
     * table, via the <code>exemptions_user_id_fkey</code> key
     */
    fun exemptionsUserIdFkey(): ExemptionsPath {
        if (!this::_exemptionsUserIdFkey.isInitialized)
            _exemptionsUserIdFkey = ExemptionsPath(this, null, EXEMPTIONS__EXEMPTIONS_USER_ID_FKEY.inverseKey)

        return _exemptionsUserIdFkey;
    }

    val exemptionsUserIdFkey: ExemptionsPath
        get(): ExemptionsPath = exemptionsUserIdFkey()
    override fun `as`(alias: String): Users = Users(DSL.name(alias), this)
    override fun `as`(alias: Name): Users = Users(alias, this)
    override fun `as`(alias: Table<*>): Users = Users(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Users = Users(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Users = Users(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Users = Users(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Users = Users(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Users = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Users = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Users = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Users = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Users = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Users = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Users = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Users = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Users = where(DSL.notExists(select))
}
