@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package er.codes.secretsaltyminimal.jooq.keys


import er.codes.secretsaltyminimal.jooq.tables.Assignments
import er.codes.secretsaltyminimal.jooq.tables.Exemptions
import er.codes.secretsaltyminimal.jooq.tables.Users
import er.codes.secretsaltyminimal.jooq.tables.records.AssignmentsRecord
import er.codes.secretsaltyminimal.jooq.tables.records.ExemptionsRecord
import er.codes.secretsaltyminimal.jooq.tables.records.UsersRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.QOM.ForeignKeyRule



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val ASSIGNMENTS_PKEY: UniqueKey<AssignmentsRecord> = Internal.createUniqueKey(Assignments.ASSIGNMENTS, DSL.name("assignments_pkey"), arrayOf(Assignments.ASSIGNMENTS.GIVER_ID), true)
val ASSIGNMENTS_RECEIVER_ID_KEY: UniqueKey<AssignmentsRecord> = Internal.createUniqueKey(Assignments.ASSIGNMENTS, DSL.name("assignments_receiver_id_key"), arrayOf(Assignments.ASSIGNMENTS.RECEIVER_ID), true)
val EXEMPTIONS_PKEY: UniqueKey<ExemptionsRecord> = Internal.createUniqueKey(Exemptions.EXEMPTIONS, DSL.name("exemptions_pkey"), arrayOf(Exemptions.EXEMPTIONS.USER_ID, Exemptions.EXEMPTIONS.EXCLUDED_USER_ID), true)
val USERS_PKEY: UniqueKey<UsersRecord> = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), arrayOf(Users.USERS.USER_ID), true)
val USERS_USERNAME_KEY: UniqueKey<UsersRecord> = Internal.createUniqueKey(Users.USERS, DSL.name("users_username_key"), arrayOf(Users.USERS.USERNAME), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val ASSIGNMENTS__ASSIGNMENTS_GIVER_ID_FKEY: ForeignKey<AssignmentsRecord, UsersRecord> = Internal.createForeignKey(Assignments.ASSIGNMENTS, DSL.name("assignments_giver_id_fkey"), arrayOf(Assignments.ASSIGNMENTS.GIVER_ID), er.codes.secretsaltyminimal.jooq.keys.USERS_PKEY, arrayOf(Users.USERS.USER_ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
val ASSIGNMENTS__ASSIGNMENTS_RECEIVER_ID_FKEY: ForeignKey<AssignmentsRecord, UsersRecord> = Internal.createForeignKey(Assignments.ASSIGNMENTS, DSL.name("assignments_receiver_id_fkey"), arrayOf(Assignments.ASSIGNMENTS.RECEIVER_ID), er.codes.secretsaltyminimal.jooq.keys.USERS_PKEY, arrayOf(Users.USERS.USER_ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
val EXEMPTIONS__EXEMPTIONS_EXCLUDED_USER_ID_FKEY: ForeignKey<ExemptionsRecord, UsersRecord> = Internal.createForeignKey(Exemptions.EXEMPTIONS, DSL.name("exemptions_excluded_user_id_fkey"), arrayOf(Exemptions.EXEMPTIONS.EXCLUDED_USER_ID), er.codes.secretsaltyminimal.jooq.keys.USERS_PKEY, arrayOf(Users.USERS.USER_ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
val EXEMPTIONS__EXEMPTIONS_USER_ID_FKEY: ForeignKey<ExemptionsRecord, UsersRecord> = Internal.createForeignKey(Exemptions.EXEMPTIONS, DSL.name("exemptions_user_id_fkey"), arrayOf(Exemptions.EXEMPTIONS.USER_ID), er.codes.secretsaltyminimal.jooq.keys.USERS_PKEY, arrayOf(Users.USERS.USER_ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
