@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package er.codes.secretsaltyminimal.jooq.indexes


import er.codes.secretsaltyminimal.jooq.tables.Assignments
import er.codes.secretsaltyminimal.jooq.tables.Exemptions

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IDX_ASSIGNMENTS_RECEIVER: Index = Internal.createIndex(DSL.name("idx_assignments_receiver"), Assignments.ASSIGNMENTS, arrayOf(Assignments.ASSIGNMENTS.RECEIVER_ID), false)
val IDX_EXEMPTIONS_USER: Index = Internal.createIndex(DSL.name("idx_exemptions_user"), Exemptions.EXEMPTIONS, arrayOf(Exemptions.EXEMPTIONS.USER_ID), false)
