/*
 * This file is generated by jOOQ.
 */
package er.codes.secretsaltyminimal.jooq.tables.daos


import er.codes.secretsaltyminimal.jooq.AbstractSpringDAOImpl
import er.codes.secretsaltyminimal.jooq.tables.Assignments
import er.codes.secretsaltyminimal.jooq.tables.records.AssignmentsRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Configuration
import org.springframework.stereotype.Repository


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
@Repository
open class AssignmentsDao(configuration: Configuration?) : AbstractSpringDAOImpl<AssignmentsRecord, er.codes.secretsaltyminimal.jooq.tables.pojos.Assignments, String>(Assignments.ASSIGNMENTS, er.codes.secretsaltyminimal.jooq.tables.pojos.Assignments::class.java, configuration) {

    /**
     * Create a new AssignmentsDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: er.codes.secretsaltyminimal.jooq.tables.pojos.Assignments): String? = o.giverId

    /**
     * Fetch records that have <code>giver_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfGiverId(lowerInclusive: String?, upperInclusive: String?): List<er.codes.secretsaltyminimal.jooq.tables.pojos.Assignments> = fetchRange(Assignments.ASSIGNMENTS.GIVER_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>giver_id IN (values)</code>
     */
    fun fetchByGiverId(vararg values: String): List<er.codes.secretsaltyminimal.jooq.tables.pojos.Assignments> = fetch(Assignments.ASSIGNMENTS.GIVER_ID, *values)

    /**
     * Fetch a unique record that has <code>giver_id = value</code>
     */
    fun fetchOneByGiverId(value: String): er.codes.secretsaltyminimal.jooq.tables.pojos.Assignments? = fetchOne(Assignments.ASSIGNMENTS.GIVER_ID, value)

    /**
     * Fetch records that have <code>receiver_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfReceiverId(lowerInclusive: String?, upperInclusive: String?): List<er.codes.secretsaltyminimal.jooq.tables.pojos.Assignments> = fetchRange(Assignments.ASSIGNMENTS.RECEIVER_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>receiver_id IN (values)</code>
     */
    fun fetchByReceiverId(vararg values: String): List<er.codes.secretsaltyminimal.jooq.tables.pojos.Assignments> = fetch(Assignments.ASSIGNMENTS.RECEIVER_ID, *values)

    /**
     * Fetch a unique record that has <code>receiver_id = value</code>
     */
    fun fetchOneByReceiverId(value: String): er.codes.secretsaltyminimal.jooq.tables.pojos.Assignments? = fetchOne(Assignments.ASSIGNMENTS.RECEIVER_ID, value)

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCreatedAt(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<er.codes.secretsaltyminimal.jooq.tables.pojos.Assignments> = fetchRange(Assignments.ASSIGNMENTS.CREATED_AT, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    fun fetchByCreatedAt(vararg values: LocalDateTime): List<er.codes.secretsaltyminimal.jooq.tables.pojos.Assignments> = fetch(Assignments.ASSIGNMENTS.CREATED_AT, *values)
}
