/*
 * This file is generated by jOOQ.
 */
package er.codes.secretsaltyminimal.jooq.tables.daos


import er.codes.secretsaltyminimal.jooq.AbstractSpringDAOImpl
import er.codes.secretsaltyminimal.jooq.tables.Exemptions
import er.codes.secretsaltyminimal.jooq.tables.records.ExemptionsRecord

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.Record2
import org.springframework.stereotype.Repository


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
@Repository
open class ExemptionsDao(configuration: Configuration?) : AbstractSpringDAOImpl<ExemptionsRecord, er.codes.secretsaltyminimal.jooq.tables.pojos.Exemptions, Record2<String?, String?>>(Exemptions.EXEMPTIONS, er.codes.secretsaltyminimal.jooq.tables.pojos.Exemptions::class.java, configuration) {

    /**
     * Create a new ExemptionsDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: er.codes.secretsaltyminimal.jooq.tables.pojos.Exemptions): Record2<String?, String?> = compositeKeyRecord(o.userId, o.excludedUserId)

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfUserId(lowerInclusive: String?, upperInclusive: String?): List<er.codes.secretsaltyminimal.jooq.tables.pojos.Exemptions> = fetchRange(Exemptions.EXEMPTIONS.USER_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    fun fetchByUserId(vararg values: String): List<er.codes.secretsaltyminimal.jooq.tables.pojos.Exemptions> = fetch(Exemptions.EXEMPTIONS.USER_ID, *values)

    /**
     * Fetch records that have <code>excluded_user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfExcludedUserId(lowerInclusive: String?, upperInclusive: String?): List<er.codes.secretsaltyminimal.jooq.tables.pojos.Exemptions> = fetchRange(Exemptions.EXEMPTIONS.EXCLUDED_USER_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>excluded_user_id IN (values)</code>
     */
    fun fetchByExcludedUserId(vararg values: String): List<er.codes.secretsaltyminimal.jooq.tables.pojos.Exemptions> = fetch(Exemptions.EXEMPTIONS.EXCLUDED_USER_ID, *values)
}
