/*
 * This file is generated by jOOQ.
 */
package er.codes.secretsaltyminimal.jooq.tables.daos


import er.codes.secretsaltyminimal.jooq.AbstractSpringDAOImpl
import er.codes.secretsaltyminimal.jooq.tables.Users
import er.codes.secretsaltyminimal.jooq.tables.records.UsersRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Configuration
import org.springframework.stereotype.Repository


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
@Repository
open class UsersDao(configuration: Configuration?) : AbstractSpringDAOImpl<UsersRecord, er.codes.secretsaltyminimal.jooq.tables.pojos.Users, String>(Users.USERS, er.codes.secretsaltyminimal.jooq.tables.pojos.Users::class.java, configuration) {

    /**
     * Create a new UsersDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: er.codes.secretsaltyminimal.jooq.tables.pojos.Users): String? = o.userId

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfUserId(lowerInclusive: String?, upperInclusive: String?): List<er.codes.secretsaltyminimal.jooq.tables.pojos.Users> = fetchRange(Users.USERS.USER_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    fun fetchByUserId(vararg values: String): List<er.codes.secretsaltyminimal.jooq.tables.pojos.Users> = fetch(Users.USERS.USER_ID, *values)

    /**
     * Fetch a unique record that has <code>user_id = value</code>
     */
    fun fetchOneByUserId(value: String): er.codes.secretsaltyminimal.jooq.tables.pojos.Users? = fetchOne(Users.USERS.USER_ID, value)

    /**
     * Fetch records that have <code>username BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfUsername(lowerInclusive: String?, upperInclusive: String?): List<er.codes.secretsaltyminimal.jooq.tables.pojos.Users> = fetchRange(Users.USERS.USERNAME, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    fun fetchByUsername(vararg values: String): List<er.codes.secretsaltyminimal.jooq.tables.pojos.Users> = fetch(Users.USERS.USERNAME, *values)

    /**
     * Fetch a unique record that has <code>username = value</code>
     */
    fun fetchOneByUsername(value: String): er.codes.secretsaltyminimal.jooq.tables.pojos.Users? = fetchOne(Users.USERS.USERNAME, value)

    /**
     * Fetch records that have <code>wishes BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfWishes(lowerInclusive: String?, upperInclusive: String?): List<er.codes.secretsaltyminimal.jooq.tables.pojos.Users> = fetchRange(Users.USERS.WISHES, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>wishes IN (values)</code>
     */
    fun fetchByWishes(vararg values: String): List<er.codes.secretsaltyminimal.jooq.tables.pojos.Users> = fetch(Users.USERS.WISHES, *values)

    /**
     * Fetch records that have <code>first_seen_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfFirstSeenAt(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<er.codes.secretsaltyminimal.jooq.tables.pojos.Users> = fetchRange(Users.USERS.FIRST_SEEN_AT, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>first_seen_at IN (values)</code>
     */
    fun fetchByFirstSeenAt(vararg values: LocalDateTime): List<er.codes.secretsaltyminimal.jooq.tables.pojos.Users> = fetch(Users.USERS.FIRST_SEEN_AT, *values)
}
